.\" Manpage for libkeys
.\" Contact thorsten.johannvorderbrueggen@t-online.de to correct errors or typos.
.TH libkeys 3 "20 June 2015" "0.0.1" "libkeys man page"
.SH NAME
libi2c
\-\- some useful keybord functions
.SH SYNOPSIS
.PP
#include \fI <libkeys.h>\fP
.PP
tbd ... void some_func(void);
.br
tbd ... void some_more_func(void);
.br
.PP
.SH DESCRIPTION
This functions are part of the
.BR arm926_sdk
(https://github.com/tjohann/arm926_sdk)
.PP
The functions implement some useful keyboard functions
.PP
.SH FILES
.BR libkeys.c
\- function implementation
.br
.BR libkeys.h
\- interface header
.br
.PP
.SH OPTIONS
None
.PP
.SH BUGS
No known bugs
.PP
.SH "SEE ALSO"
.BR arm926_sdk(3)
.PP
.SH AUTHOR
Thorsten Johannvorderbrueggen
.br
Email: \fB<thorsten.johannvorderbrueggen@t-online.de> \fP

