# only for cleaning :-)

.PHONY: all
all: 
	@echo Cheers

.PHONY: clean
clean:
	rm -f *~
	rm -f *.log *.aux *.log *.idx

distclean: clean

docs::
	#makeindex doc_arm926_sdk
	#latex doc_arm926_sdk 
	#dvips -o arm926_sdkt.ps doc_arm926_sdk.dvi
	#dvipdf doc_arm926_sdk.dvi arm926_sdk.pdf% Index
#	\printindex
