# only for cleaning 

all:: 
	@echo Cheers

clean::
	rm -f *~ 
	rm -f invalid/*~
	rm -f pdf/*
	rm -f html/*

distclean: clean

docs::
	@echo "+----------------------------------------------------------+"
	@echo "|                                                          |"
	@echo "|                      Build docs                          |"
	@echo "|                                                          |"
	@echo "+----------------------------------------------------------+"
